# Generated by Django 3.1.4 on 2020-12-08 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер комнаты')),
                ('name', models.CharField(max_length=64, verbose_name='Имя комнаты')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_from', models.DateTimeField(verbose_name='Начало брони')),
                ('datetime_to', models.DateTimeField(verbose_name='Конец брони')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, поставивший бронь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room', verbose_name='Забронированная комната')),
            ],
        ),
    ]
