# Generated by Django 3.1.4 on 2020-12-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты'),
        ),
    ]
